apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/tags: ""
  creationTimestamp: null
  name: calvin
  namespace: vela-system
spec:
  components:
  - name: calvin-qc-newapi2-api
    properties:
      addRevisionLabel: false
      cpu: "0.5"
      exposeType: ClusterIP
      image: nginx
      imagePullPolicy: IfNotPresent
      memory: 199Mi
      ports:
      - expose: true
        name: http
        port: 80
        protocol: TCP
    traits:
    - properties:
        class: nginx
        classInSpec: false
        http:
          "1": 2
      type: gateway
    type: webservice
status: {}
