apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/app: dev
    application.deploy.reform/tags: ""
  creationTimestamp: null
  name: calvin-qc
  namespace: vela-system
spec:
  components:
  - name: calvin-qc-web-wizard-web-web
    properties:
      domain: devs.com.hk
      path: ad
      resource: Medium
      secure: false
    type: web-wizard-web
status: {}
