apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/tags: ""
  creationTimestamp: null
  name: qc-test-cal
  namespace: vela-app
spec:
  components:
  - name: qc-test-cal-test-web
    properties:
      domain: dev.com.hk
      path: ag
      resource: Medium
      secure: false
    type: web-wizard-web
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
