apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/tags: ""
  creationTimestamp: null
  name: qc-calvin
  namespace: vela-app
spec:
  components:
  - name: qc-calvin-web-wizard-api-api
    properties:
      domain: dev.com.hk
      expose: false
      path: as
      resource: Medium
      secure: false
    type: web-wizard-api
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
