apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/cluster: local
    application.deploy.reform/commitHash: 5ef9ee88a9a2b4cabe72aec1e905a0f7fd534892
    application.deploy.reform/deploymentNo: qc-test-cal-local_DP1
    application.deploy.reform/environment: local
    application.deploy.reform/name: qc-test-cal
    application.deploy.reform/repository: https://github.com/Gglayolun/Devtest.git
    application.deploy.reform/repositoryPath: ag
    application.deploy.reform/revision: 2023.04.1
    application.deploy.reform/tags: ""
    deploy.reform/domain: ""
    deploy.reform/version: 6b5c82cf8fbd6720e41370072c0193f4158e3f6c
  creationTimestamp: null
  name: qc-test-cal
  namespace: vela-app
spec:
  components:
  - name: qc-test-cal-test-web
    properties:
      domain: dev.com.hk
      path: ag
      resource: Medium
      secure: false
    type: web-wizard-web
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
