apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/app: dev-1
    application.deploy.reform/cluster: local
    application.deploy.reform/commitHash: 8f894dce494f3c4974e0fe489265a5f1c8cfed1d
    application.deploy.reform/deploymentNo: qc2-calvin-local_DP1
    application.deploy.reform/environment: local
    application.deploy.reform/name: qc2-calvin
    application.deploy.reform/repository: https://github.com/Gglayolun/Devtest.git
    application.deploy.reform/repositoryPath: aa
    application.deploy.reform/revision: 2023.04.1
    application.deploy.reform/tags: ""
    deploy.reform/domain: ""
    deploy.reform/version: 6b5c82cf8fbd6720e41370072c0193f4158e3f6c
  creationTimestamp: null
  name: qc2-calvin
  namespace: vela-app
spec:
  components:
  - name: qc2-calvin-web-wizard-web-web
    properties:
      domain: static.com
      path: aa
      resource: Medium
      secure: false
    type: web-wizard-web
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
